import "./modules/add-to-fav";
import "@pug/sections/top-banner/top-banner";
import "@pug/sections/catalog/catalog-detail/catalog-detail-slider";
import "@pug/components/_ui/sliders/base-slider/base-slider";
import "@pug/components/_ui/cards/product-card/product-card-inner-slider";
import "@pug/components/_ui/cards/product-card/product-card-add-cart-btn";
import "@pug/components/_ui/cards/product-card/product-size-chooser";
import "@pug/components/_ui/buttons/color-picker-btn-row/color-picker-chooser";
import "@pug/components/_ui/accordeon/accordeon";
